require:
  - 'ts-node/register'
# - "source-map-support/register"
# full-trace: true
spec:
  - 'packages/**/*.spec.ts'
  - 'packages/**/*.spec.tsx'
ignore:
  - 'packages/*/node_modules/**/*'
extension:
  - 'ts'
  - 'tsx'
watch-files:
  - 'packages/*/src'
