include:
  - 'packages/*/src/**/*.ts'
  - 'packages/*/src/**/*.tsx'
exclude:
  - 'packages/*/src/**/*.spec.ts'
  - 'packages/*/src/**/*.spec.tsx'
extension:
  - '.ts'
  - '.tsx'
reporter:
  - 'text-summary'
  - 'lcov'
sourceMap: true
instrument: true
